let shopData = {
    results: [
        {
            id: 525,
            title: "ULTRA MEGA PRO 999 RUNNING TREADMILL",
            brand: "BhFitness",
            favorite: "../assets/shop.png",
            imageUrl: "../assets/650_1200.webp",
        },
        {
            id: 526,
            title: "Xcalibur EMS Smart Bike",
            brand: "TechnoGym",
            favorite: "../assets/shop.png",
            imageUrl: "../assets/6652520389662785.webp",
        },
        {
            id: 527,
            title: "TF30 FOLDING TAPE WITH XIR CONSOLE",
            brand: "MATRIX",
            favorite: "../assets/shop.png",
            imageUrl: "../assets/bicicleta-fija.jpg",
        },
        {
            id: 528,
            title: "Xcalibur Magnétic Smart Bike",
            brand: "BhFitness",
            favorite: "../assets/shop.png",
            imageUrl:  "../assets/Multigym-500-Behumax.jpg",
        },
        {
            id: 529,
            title: "PLATINUM CLUB SERIES TREADMILL",
            brand:  "Tunturi",
            favorite: "../assets/shop.png",
            imageUrl: "../assets/E5006-PRESION-HOMBRO.png",
        },
        {
            id: 530,
            title: "ACTIVATE SERIES LIFECYCLE VERTICAL EXERCISE BIKE",
            brand:"MATRIX",
            favorite: "../assets/shop.png",
            imageUrl: "../assets/optimized---Go.png",
        },
        {
            id: 531,
            title: "ULTRA MEGA PRO 999 RUNNING TREADMILL",
            brand: "BhFitness",
            favorite: "../assets/shop.png",
            imageUrl: "../assets/650_1200.webp",
        },
        {
            id: 532,
            title: "Xcalibur EMS Smart Bike",
            brand: "TechnoGym",
            favorite: "../assets/shop.png",
            imageUrl: "../assets/6652520389662785.webp",
        },
        {
            id: 533,
            title: "TF30 FOLDING TAPE WITH XIR CONSOLE",
            brand: "MATRIX",
            favorite: "../assets/shop.png",
            imageUrl: "../assets/bicicleta-fija.jpg",
        },
        {
            id: 534,
            title: "Xcalibur Magnétic Smart Bike",
            brand: "BhFitness",
            favorite: "../assets/shop.png",
            imageUrl:  "../assets/Multigym-500-Behumax.jpg",
        },
        {
            id: 535,
            title: "PLATINUM CLUB SERIES TREADMILL",
            brand:  "Tunturi",
            favorite: "../assets/shop.png",
            imageUrl: "../assets/E5006-PRESION-HOMBRO.png",
        },
        {
            id: 536,
            title: "ACTIVATE SERIES LIFECYCLE VERTICAL EXERCISE BIKE",
            brand:"MATRIX",
            favorite: "../assets/shop.png",
            imageUrl: "../assets/optimized---Go.png",
        },
        {
            id: 537,
            title: "ULTRA MEGA PRO 999 RUNNING TREADMILL",
            brand: "BhFitness",
            favorite: "../assets/shop.png",
            imageUrl: "../assets/650_1200.webp",
        },
        {
            id: 538,
            title: "Xcalibur EMS Smart Bike",
            brand: "TechnoGym",
            favorite: "../assets/shop.png",
            imageUrl: "../assets/6652520389662785.webp",
        },
        {
            id: 539,
            title: "TF30 FOLDING TAPE WITH XIR CONSOLE",
            brand: "MATRIX",
            favorite: "../assets/shop.png",
            imageUrl: "../assets/bicicleta-fija.jpg",
        },
        {
            id: 540,
            title: "Xcalibur Magnétic Smart Bike",
            brand: "BhFitness",
            favorite: "../assets/shop.png",
            imageUrl:  "../assets/Multigym-500-Behumax.jpg",
        },
        {
            id: 541,
            title: "PLATINUM CLUB SERIES TREADMILL",
            brand:  "Tunturi",
            favorite: "../assets/shop.png",
            imageUrl: "../assets/E5006-PRESION-HOMBRO.png",
        },
        {
            id: 542,
            title: "ACTIVATE SERIES LIFECYCLE VERTICAL EXERCISE BIKE",
            brand:"MATRIX",
            favorite: "../assets/shop.png",
            imageUrl: "../assets/optimized---Go.png",
        },
    ]
}